/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "G:\\学习\\vue2.6.12-code-study\\vue-notes\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-4af0e625",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4af0e625").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-7021b638",
    path: "/guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7021b638").then(next)
    },
  },
  {
    path: "/guide/index.html",
    redirect: "/guide/"
  },
  {
    name: "v-327d3570",
    path: "/vue-code-study/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-327d3570").then(next)
    },
  },
  {
    path: "/vue-code-study/index.html",
    redirect: "/vue-code-study/"
  },
  {
    name: "v-4bc7bf50",
    path: "/vue-code-study/compile/compile-flow.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4bc7bf50").then(next)
    },
  },
  {
    name: "v-2ad8d1a2",
    path: "/vue-code-study/compile/compile-entry.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2ad8d1a2").then(next)
    },
  },
  {
    name: "v-034182e4",
    path: "/vue-code-study/compile/ast.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-034182e4").then(next)
    },
  },
  {
    name: "v-dabf4c94",
    path: "/vue-code-study/compile/mark-static.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-dabf4c94").then(next)
    },
  },
  {
    name: "v-7aadae70",
    path: "/vue-code-study/compile/events.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7aadae70").then(next)
    },
  },
  {
    name: "v-27dfc220",
    path: "/vue-code-study/compile/parse-html.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-27dfc220").then(next)
    },
  },
  {
    name: "v-23735380",
    path: "/vue-code-study/compile/model.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-23735380").then(next)
    },
  },
  {
    name: "v-9793e8a8",
    path: "/vue-code-study/compile/parse.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9793e8a8").then(next)
    },
  },
  {
    name: "v-11ca359c",
    path: "/vue-code-study/global-api/global.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-11ca359c").then(next)
    },
  },
  {
    name: "v-59481420",
    path: "/vue-code-study/compile/generate.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-59481420").then(next)
    },
  },
  {
    name: "v-ae2cf320",
    path: "/vue-code-study/entry/entry.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ae2cf320").then(next)
    },
  },
  {
    name: "v-63641d32",
    path: "/vue-code-study/entry/state.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-63641d32").then(next)
    },
  },
  {
    name: "v-8ada39e4",
    path: "/vue-code-study/question/q1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8ada39e4").then(next)
    },
  },
  {
    name: "v-74816816",
    path: "/vue-code-study/render/create-component.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-74816816").then(next)
    },
  },
  {
    name: "v-629a4af0",
    path: "/vue-code-study/observe/observe.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-629a4af0").then(next)
    },
  },
  {
    name: "v-2c205ec2",
    path: "/vue-code-study/render/render.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2c205ec2").then(next)
    },
  },
  {
    name: "v-e0a8c944",
    path: "/vue-code-study/observe/queue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e0a8c944").then(next)
    },
  },
  {
    name: "v-4bb5d510",
    path: "/vue-code-study/global-api/instance.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4bb5d510").then(next)
    },
  },
  {
    name: "v-5f7d1dbc",
    path: "/vue-code-study/util/shared.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5f7d1dbc").then(next)
    },
  },
  {
    name: "v-8780a5e0",
    path: "/vue-code-study/util/web-util.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8780a5e0").then(next)
    },
  },
  {
    name: "v-3c4c4782",
    path: "/vue-code-study/util/util.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3c4c4782").then(next)
    },
  },
  {
    name: "v-27c77576",
    path: "/vue-code-study/render/virtual-dom.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-27c77576").then(next)
    },
  },
  {
    name: "v-038d81dc",
    path: "/vue-code-study/window-api/window.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-038d81dc").then(next)
    },
  },
  {
    name: "v-5efd9ed8",
    path: "/vue-code-study/render/create-element.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5efd9ed8").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]