/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "笔记",
  "description": "write by kfg",
  "base": "/vue-notes/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/images/logo.png",
        "actionText": "快速上手 →",
        "actionLink": "/guide/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-19aff440",
      "path": "/"
    },
    {
      "title": "开始之前",
      "frontmatter": {},
      "regularPath": "/vue-code-study/",
      "relativePath": "vue-code-study/README.md",
      "key": "v-e67ddbba",
      "path": "/vue-code-study/"
    },
    {
      "frontmatter": {},
      "regularPath": "/guide/",
      "relativePath": "guide/readme.md",
      "key": "v-6a8d73d3",
      "path": "/guide/"
    },
    {
      "title": "vue入口",
      "frontmatter": {},
      "regularPath": "/vue-code-study/entry/entry.html",
      "relativePath": "vue-code-study/entry/entry.md",
      "key": "v-13d7ff16",
      "path": "/vue-code-study/entry/entry.html",
      "headers": [
        {
          "level": 2,
          "title": "入口文件",
          "slug": "入口文件"
        },
        {
          "level": 2,
          "title": "initMixin",
          "slug": "initmixin"
        },
        {
          "level": 3,
          "title": "resolveConstructorOptions",
          "slug": "resolveconstructoroptions"
        },
        {
          "level": 2,
          "title": "mergeOptions",
          "slug": "mergeoptions"
        },
        {
          "level": 3,
          "title": "默认合并策略",
          "slug": "默认合并策略"
        },
        {
          "level": 3,
          "title": "el，propsData合并策略",
          "slug": "el-propsdata合并策略"
        },
        {
          "level": 3,
          "title": "data，provide合并策略",
          "slug": "data-provide合并策略"
        },
        {
          "level": 3,
          "title": "生命周期合并策略",
          "slug": "生命周期合并策略"
        },
        {
          "level": 3,
          "title": "props，methods，inject，computed合并策略",
          "slug": "props-methods-inject-computed合并策略"
        },
        {
          "level": 3,
          "title": "directives，filters，components合并策略",
          "slug": "directives-filters-components合并策略"
        },
        {
          "level": 3,
          "title": "watch合并策略",
          "slug": "watch合并策略"
        },
        {
          "level": 2,
          "title": "initProvide，initInjections",
          "slug": "initprovide-initinjections"
        }
      ]
    },
    {
      "title": "entry",
      "frontmatter": {},
      "regularPath": "/vue-code-study/entry/",
      "relativePath": "vue-code-study/entry/readme.md",
      "key": "v-2adf1d76",
      "path": "/vue-code-study/entry/",
      "headers": [
        {
          "level": 2,
          "title": "entry",
          "slug": "entry"
        }
      ]
    },
    {
      "title": "全局方法",
      "frontmatter": {},
      "regularPath": "/vue-code-study/global-api/global.html",
      "relativePath": "vue-code-study/global-api/global.md",
      "key": "v-099cd021",
      "path": "/vue-code-study/global-api/global.html",
      "headers": [
        {
          "level": 2,
          "title": "Vue.extend",
          "slug": "vue-extend"
        },
        {
          "level": 2,
          "title": "Vue.mixin",
          "slug": "vue-mixin"
        }
      ]
    },
    {
      "title": "shared目录",
      "frontmatter": {},
      "regularPath": "/vue-code-study/util/shared.html",
      "relativePath": "vue-code-study/util/shared.md",
      "key": "v-a6b0d07e",
      "path": "/vue-code-study/util/shared.html",
      "headers": [
        {
          "level": 2,
          "title": "常量",
          "slug": "常量"
        },
        {
          "level": 2,
          "title": "isObject",
          "slug": "isobject"
        },
        {
          "level": 2,
          "title": "toRawType",
          "slug": "torawtype"
        },
        {
          "level": 2,
          "title": "isPlainObject",
          "slug": "isplainobject"
        },
        {
          "level": 2,
          "title": "makeMap",
          "slug": "makemap"
        },
        {
          "level": 2,
          "title": "isBuiltInTag",
          "slug": "isbuiltintag"
        },
        {
          "level": 2,
          "title": "isReservedAttribute",
          "slug": "isreservedattribute"
        },
        {
          "level": 2,
          "title": "hasOwn",
          "slug": "hasown"
        },
        {
          "level": 2,
          "title": "cached",
          "slug": "cached"
        },
        {
          "level": 2,
          "title": "camelize",
          "slug": "camelize"
        },
        {
          "level": 2,
          "title": "capitalize",
          "slug": "capitalize"
        },
        {
          "level": 2,
          "title": "hyphenate",
          "slug": "hyphenate"
        },
        {
          "level": 2,
          "title": "bind",
          "slug": "bind"
        },
        {
          "level": 2,
          "title": "extend",
          "slug": "extend"
        },
        {
          "level": 2,
          "title": "noop",
          "slug": "noop"
        },
        {
          "level": 2,
          "title": "no",
          "slug": "no"
        }
      ]
    },
    {
      "title": "数据响应式",
      "frontmatter": {},
      "regularPath": "/vue-code-study/entry/state.html",
      "relativePath": "vue-code-study/entry/state.md",
      "key": "v-9ee2d192",
      "path": "/vue-code-study/entry/state.html",
      "headers": [
        {
          "level": 2,
          "title": "initState",
          "slug": "initstate"
        },
        {
          "level": 3,
          "title": "initProps",
          "slug": "initprops"
        },
        {
          "level": 3,
          "title": "initMethods",
          "slug": "initmethods"
        },
        {
          "level": 3,
          "title": "initData",
          "slug": "initdata"
        }
      ]
    },
    {
      "title": "util目录",
      "frontmatter": {},
      "regularPath": "/vue-code-study/util/util.html",
      "relativePath": "vue-code-study/util/util.md",
      "key": "v-be32e7f2",
      "path": "/vue-code-study/util/util.html",
      "headers": [
        {
          "level": 2,
          "title": "env.js",
          "slug": "env-js"
        },
        {
          "level": 3,
          "title": "nativeWatch",
          "slug": "nativewatch"
        },
        {
          "level": 3,
          "title": "isNative",
          "slug": "isnative"
        },
        {
          "level": 3,
          "title": "hasSymbol",
          "slug": "hassymbol"
        },
        {
          "level": 2,
          "title": "props.js",
          "slug": "props-js"
        },
        {
          "level": 3,
          "title": "validateProp",
          "slug": "validateprop"
        },
        {
          "level": 3,
          "title": "getPropDefaultValue",
          "slug": "getpropdefaultvalue"
        },
        {
          "level": 3,
          "title": "assertProp",
          "slug": "assertprop"
        },
        {
          "level": 3,
          "title": "assertType",
          "slug": "asserttype"
        },
        {
          "level": 3,
          "title": "getTypeIndex",
          "slug": "gettypeindex"
        },
        {
          "level": 3,
          "title": "getInvalidTypeMessage",
          "slug": "getinvalidtypemessage"
        }
      ]
    },
    {
      "title": "performance",
      "frontmatter": {},
      "regularPath": "/vue-code-study/window-api/window.html",
      "relativePath": "vue-code-study/window-api/window.md",
      "key": "v-093fc73e",
      "path": "/vue-code-study/window-api/window.html"
    }
  ],
  "themeConfig": {
    "sidebar": {
      "/vue-code-study/": [
        {
          "title": "前言",
          "collapsable": false,
          "sidebarDepth": 1,
          "children": [
            ""
          ]
        },
        {
          "title": "初始化过程",
          "collapsable": false,
          "children": [
            "entry/entry",
            "entry/state"
          ],
          "sidebarDepth": 2
        },
        {
          "title": "全局方法",
          "collapsable": false,
          "children": [
            "global-api/global"
          ]
        },
        {
          "title": "工具函数",
          "collapsable": false,
          "children": [
            "util/util",
            "util/shared"
          ],
          "sidebarDepth": 2
        },
        {
          "title": "window接口",
          "collapsable": false,
          "children": [
            "window-api/window"
          ]
        }
      ]
    },
    "logo": "/images/logo.png",
    "nav": [
      {
        "text": "Home",
        "link": "/"
      },
      {
        "text": "vue源码",
        "link": "/vue-code-study/"
      }
    ]
  }
}